#!/bin/bash


  env_is_secure="true"
  env_test_port="443"
  env_test_domain="example.com"
  env_test_start="/"

  env_links_published=(
    "favicon/flaticon_com_flowers_ico/022_lily.ico"
    "favicon/flaticon_com_flowers_ico/042_pea.ico"
  )


